services:
  rabbitmq:
    container_name: rabbit
    image: rabbitmq:3.13.6-management
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitmq
      - RABBITMQ_DEFAULT_PASS=12345678